name: Build
on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Set up Java
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: 'liberica'
          java-version: 17
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Gradle
        uses: step-security/gradle-actions/setup-gradle@2dbaa2a58bd4447c762ed6e6a89a25f7c2a85f80 # v5.0.1
        with:
          cache-read-only: false
      - name: Build
        id: build
        run: ./gradlew build
